export default {
  border: {
    radius: {
      xsmall: 4,
      small: 8,
      medium: 10,
      large: 20,
    },
  },
  font: {
    family: {
      bold: 'FiraSans-Bold',
      boldItalic: 'FiraSans-BoldItalic',
      italic: 'FiraSans-Italic',
      medium: 'FiraSans-Medium',
      mediumItalic: 'FiraSans-MediumItalic',
      regular: 'FiraSans-Regular',
      semiBold: 'FiraSans-SemiBold',
      semiBoldItalic: 'FiraSans-SemiBoldItalic',
    },
    wight: {
      light: 300,
      normal: 400,
      bold: 600,
      xbold: 700,
    },
    sizes: {
      xsmall: 10,
      small: 14,
      medium: 16,
      large: 20,
      xlarge: 24,
      xxlarge: 28,
    },
  },
  colors: {
    primary: '#F231A5',
    secondary: '#3CD3C1',
    mainBg: '#06092B',
    lightBg: '#F2F2F2',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
    red: '#FF6347',
  },
  spacings: {
    xxsmall: 8,
    xsmall: 14,
    medium: 16,
    large: 20,
    xlarge: 28,
    xxlarge: 32,
    huge: 44,
  },
} as const;
