export default {
  border: {
    radius: {
      xsmall: 4,
      small: 8,
      medium: 10,
      large: 20,
    },
  },
  font: {
    family: {
      title: 'PlayfairDisplay-regular',
      titleItalic: 'PlayfairDisplay-Italic',
      italic: 'Poppins-Italic',
      medium: 'Poppins-Medium',
      mediumItalic: 'Poppins-MediumItalic',
      regular: 'Poppins-Regular',
      semiBold: 'Poppins-SemiBold',
      semiBoldItalic: 'Poppins-SemiBoldItalic',
    },
    wight: {
      light: 300,
      normal: 400,
      bold: 600,
      xbold: 700,
    },
    sizes: {
      xsmall: 12,
      small: 14,
      medium: 16,
      large: 20,
      xlarge: 24,
      xxlarge: 28,
      huge: 32,
    },
  },
  colors: {
    primary: '#F231A5',
    secondary: '#3CD3C1',
    mainBg: '#EFEFEF',
    lightBg: '#06092B',
    white: '#FAFAFA',
    black: '#000000',
    lightGray: '#E1E1E1',
    gray: '#545454',
    darkGray: '#2E2F42',
    red: '#A74141',
  },
  spacings: {
    xxsmall: 8,
    xsmall: 14,
    medium: 16,
    large: 20,
    xlarge: 28,
    xxlarge: 32,
    huge: 44,
  },
} as const;
